# Generated by Django 4.2.29 on 2026-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='custom_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('salary', 'Salary'), ('transport', 'Transport'), ('rent', 'Rent'), ('other', 'Other')], max_length=50),
        ),
    ]
