# Generated by Django 4.2.29 on 2026-04-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_custom_category_alter_record_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('salary', 'Salary'), ('transport', 'Transport'), ('rent', 'Rent'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=10),
        ),
    ]
